name: Release ZIPer and Version adder

on: 
  release:
    types: [published]

jobs:
  update_and_zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get release version
        id: get_version
        run: echo "::set-output name=VERSION::${{ github.event.release.tag_name }}"

      - name: Update JSON with version
        uses: replace/replace@v1
        with:
          path: your_file.json  # Replace with the path to your JSON file
          replace: '{{ver}}'
          with: ${{ steps.get_version.outputs.VERSION }}

      - name: Zip folder
        uses: mazda/github-action-zip@v2
        with:
          files: Lively/*  # Replace with the path to your folder
          filename: lively-${{ steps.get_version.outputs.VERSION }}.zip  # Replace with desired zip filename

      - name: Add zip to release assets
        uses: actions/upload-artifact@v3
        with:
          name: lively-wallpaper-${{ steps.get_version.outputs.VERSION }}
          path: lively-${{ steps.get_version.outputs.VERSION }}.zip
