name: Release ZIPer and Version adder

on: 
  release:
    types: [published]

jobs:
  update_and_zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get release version
        id: get_version
        run: echo "::set-output name=VERSION::${{ github.event.release.tag_name }}"

      - name: Update JSON with version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: Lively/LivelyInfo.json  # Replace with the path to your JSON file
          find: '{{ver}}'
          replace: ${{ steps.get_version.outputs.VERSION }}
          regex: false

      - name: Zip folder
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r lively-${{ steps.get_version.outputs.VERSION }}.zip Lively

      - name: Upload Lively to Github release
        id: upload-release-asset 
        uses: Shopify/upload-to-release@v1
        with:
          name: lively-wallpaper-${{ steps.get_version.outputs.VERSION }}
          path: lively-${{ steps.get_version.outputs.VERSION }}.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
